apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: twelve
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: twelve
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
