apiVersion: v1
kind: Service
metadata:
  name: twelve
  annotations:
    cloud.google.com/neg: '{"exposed_ports":{"8080":{}}}'
spec:
  selector:
    app: twelve
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
